//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Surname { get; set; }
        [Required]
        public string Position { get; set; }

        public Nullable<bool> Deleted { get; set; }

        public bool Equals(Employee employee)
        {
            return Name.Equals(employee.Name) &&
                   Surname.Equals(employee.Surname) &&
                   Position.Equals(employee.Position) &&
                   (Deleted == null || Deleted == false);
        }
    }
}
